version: "3.7"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: screencapDb
      MYSQL_USER: cclee
      MYSQL_PASSWORD: ccleedb12345
      MYSQL_ROOT_PASSWORD: ccleedb12345
    volumes:
      - screencapDb:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  screencapDb:
